### ISSUE TITLE
Bagnon uses a new API for integrating plugins

### ISSUE THREAD

**Issue by CMcFadyen** [AzeriteTeam/Bagnon_ItemLevel#4] opened 2019-12-27 23:41 UTC
And this addon is not compatible with that API anymore, so it causes errors.

**Comment by bryansray** [comment] 2019-12-29 16:31
I believe this is a duplicate of #2 and resolved by PR #3

**Comment by goldpaw** [comment] 2020-01-09 08:24
Fixed

**Closed by goldpaw** 2020-01-09 08:24 UTC
